### ISSUE TITLE
table 圆角

### ISSUE THREAD

**Issue by juliamachinelearning** [mdnice/markdown-nice#103]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**Markdown文本内容：**

例如：

```md
table {
    border-radius: 6px;
}
```

**错误详情：**

不起效果，希望修复。

**Comment by ZQ-jhon** [comment]
```css
/* try to add css in custom style: */
table {
border-collapse: separate !important;
border-spacing: 0;
}

/** 左上角边框 */
table tr:first-child th:first-child {
border-top-left-radius: 12px;
}
/** 右上角边框 */
table tr:first-child th:last-child {
border-top-right-radius: 12px;
}
/** 左下角边框 */
table tr:last-child td:first-child {
border-bottom-left-radius: 12px;
}
/** 右下角边框 */
table tr:last-child td:last-child {
border-bottom-right-radius: 12px;
}
```

**Comment by acccco** [comment]
这样就好了
```css
table{
    display: block;
    border-radius: 10px;
    overflow: hidden;
}
```

**Comment by ZQ-jhon** [comment]
> 这样就好了
> 
> ```css
> table{
>     display: block;
>     border-radius: 10px;
>     overflow: hidden;
> }
> ```

![image](https://user-images.githubusercontent.com/26297704/68096121-aa545780-fee9-11e9-8e37-8a3bafb32c6e.png)
Looks like some issue with corner radius

**Comment by ZQ-jhon** [comment]
> > 这样就好了
> > ```css
> > table{
> >     display: block;
> >     border-radius: 10px;
> >     overflow: hidden;
> > }
> > ```
> 
> ![image](https://user-images.githubusercontent.com/26297704/68096121-aa545780-fee9-11e9-8e37-8a3bafb32c6e.png)
> I'm cleaning all style code, and replace code 
> Looks like some issue with corner radius

**Comment by ZQ-jhon** [comment]
> > > 这样就好了
> > > ```css
> > > table{
> > >     display: block;
> > >     border-radius: 10px;
> > >     overflow: hidden;
> > > }
> > > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/26297704/68096121-aa545780-fee9-11e9-8e37-8a3bafb32c6e.png)

 I'm cleaning all style code, and replace code
 Looks like some issue with corner radius

**Comment by acccco** [comment]
嗯，测的时候没看仔细。


```css
table {
    overflow: hidden;
    box-shadow: 0 0 2px grey;
    border: 1px solid #fff;
    border-radius: 10px;
}
```

<img width="763" alt="截屏2019-11-04下午2 19 54" src="https://user-images.githubusercontent.com/12695799/68102543-2e203b00-ff0e-11e9-9972-6e5a1d75de36.png">

这样应该没问题。
