### ISSUE TITLE
标题多个背景图问题

### ISSUE THREAD

**Issue by juliamachinelearning** [mdnice/markdown-nice#110]
**运行环境：**

|操作系统|浏览器|
|---|---|
|Linux|Chrome|

**Markdown文本内容：**

例如：

**错误详情：**

css 里 h1 h2 h3这里设置两个背景图。

mdnice里显示正常，左右各一个背景图
![image](https://user-images.githubusercontent.com/57283909/68562277-e9535180-0483-11ea-9e5c-3d3d6eb455ce.png)

但是到微信里，右边的消失了。

![image](https://user-images.githubusercontent.com/57283909/68562331-261f4880-0484-11ea-93be-d440dfcee91f.png)

**Comment by guanpengchn** [comment]
@juliamachinelearning 请给下具体的css和markdown，要不不好排查

**Comment by juliamachinelearning** [comment]
例如：
css，
```
#nice h2 {
   background-image:url(https://qiniu.mdnice.com/397ff8ead8592e1bce7a7d5a6c19f012.png),url(https://qiniu.mdnice.com/b26355dc14c1b782031ef922d00ec5f3.png);
   background-position: left center, right center;
   background-repeat: no-repeat, no-repeat;
   background-size: 45xp, 45px;
   padding: 0 45px;
   height: 45px; 
   line-height: 64px; 
}
```

markdown，
```
## 二 级 标 题 
```

**Comment by views63** [comment]
第二个背景图被公众号过滤掉了。解决办法：

1. 插入代码；
2. 两张图分开，增加一个 after

**Comment by juliamachinelearning** [comment]
> 第二个背景图被公众号过滤掉了。解决办法：
> 
> 1. 插入代码；
> 2. 两张图分开，增加一个 after

你好，h2:after 试了没效果，mdnice图片没显示，能给个css代码吗，谢谢啦。

**Comment by views63** [comment]
```css
#nice h2 {
  background-image:url(https://qiniu.mdnice.com/397ff8ead8592e1bce7a7d5a6c19f012.png);
   background-position: left center;
   background-repeat: no-repeat;
   background-size: 45xp;
   padding: 0 45px;
   height: 45px; 
   line-height: 64px; 
}
/* 二级标题修饰 请参考有实例的主题 */
#nice h2:after {
 content:"";
 background-image:url(https://qiniu.mdnice.com/b26355dc14c1b782031ef922d00ec5f3.png); 
  background-repeat:no-repeat;  
  width:64px;
  height:64px;
  float:right;
}
```
看喜好自己微调吧
