### ISSUE TITLE
非微信代码主题，点击微信图标复制，然后粘贴到公众号，YAML格式缺少空格

### ISSUE THREAD

**Issue by wanghkkk** [mdnice/markdown-nice#150]
**运行环境：**

|操作系统|浏览器|

|windows|chrome|

**Markdown文本内容：**
---------------------------------
我们在创建测试用Pod：

``` yaml
cat testlogs-pods.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        args:
        - num=1;while true;do echo "{\"mydate\":\"$(date)\",\"num\":$((num=num+1))}";sleep 5;done
```
---------------------------------
**错误详情：**
没有错误提示，只是没有空格，显示如下：
只有在微信代码主题的时候没有问题。但是通过全选复制的方式也是没有问题的。同时测试过chrome插件，也是同样的问题。
![image](https://user-images.githubusercontent.com/21187778/75761861-be637500-5d74-11ea-892d-7f785cc295b8.png)

![image](https://user-images.githubusercontent.com/21187778/75751776-40966e00-5d62-11ea-9d40-22fdabfeb0c6.png)
