### ISSUE TITLE
添加新主题-灵动蓝

### ISSUE THREAD

**Issue by cumt-robin** [mdnice/markdown-nice#195]
# 主题推荐

<a name="9aa8afd2"></a>
## 主题介绍

<br />hello，很喜欢mdnice，一直在魔改主题的路上，现在提供的很多主题都非常棒，但是如果想要定制有透明度的一级标题背景图，还不是一件很简单的事情。<br />
<br />我们知道，现在的萌绿和前端之巅主题都可以在一级标题上定义一个背景图，非常好看。但是对于不擅长处理图片的人来说，有点小难度。因为这两个主题都要求图片本身有是透明度，而很多人并不会PS。<br />
<br />所以我想到用opacity去做这个透明效果，但有一点要注意的，不能给h1整体一个opacity，否则标题文字也会有透明度。所以只能把背景图放在伪元素，或者一个class=prefix的span上。然后用css来实现水平居中效果。<br />

```css
position: absolute;
top: 50%;
transform: translateX(-50%);
```

<br />![image.png](https://cdn.nlark.com/yuque/0/2020/png/319482/1590715895780-71db0f25-83da-45b7-b8a2-0036e9a7f808.png#align=left&display=inline&height=522&margin=%5Bobject%20Object%5D&name=image.png&originHeight=522&originWidth=698&size=35641&status=done&style=none&width=698)<br />但是在微信公号的编辑器保存后都出现了位置不对的问题。编辑的时候是没有问题的，一旦保存，就会发现背景图跑到最左侧了。因为微信公号的编辑器在保存后会忽略掉绝对定位position: absolute以及css3的transform。

所以就不能用绝对定位和transform去做了，只能改用其他定位和样式去做了。目前自测完全可以应用到微信编辑器上。

**总结一下：这款主题除了自定义了一些样式之外，最主要是支持标题背景图透明度可自定义，大家可以在这个基础上换自己的logo或者背景图，免去了ps修改透明度的麻烦。主题名称暂定“灵动蓝”，希望得到收录！**

<a name="isB5u"></a>
## 主题css
```css
/*自定义样式，实时生效*/

/* 全局属性 */
.nice-wx-box {

}

#nice {
  color: #333;
  font-family: -apple-system,system-ui,BlinkMacSystemFont,Helvetica Neue,PingFang SC,Hiragino Sans GB,Microsoft YaHei,Arial,sans-serif;
}

/* 标题的通用设置 */
#nice h1,
#nice h2,
#nice h3,
#nice h4,
#nice h5,
#nice h6 {
  padding: 30px 0;
  margin: 0;
  color: #135ce0;
}

/* 一级标题 */
#nice h1 {
  position: relative;
  margin-top: 30px;
  margin-bottom: 10px;
  text-align: center;
}

/* 一级标题前缀，用来放背景图，支持透明度控制 */
#nice h1 .prefix {
  display: inline-block;
  top: 0;
  width: 60px;
  height: 60px;
  background: url(http://qncdn.wbjiang.cn/ape_blue.svg);
  background-size: 100% 100%;
  opacity: .12;
}

/* 一级标题内容 */
#nice h1 .content {
  font-size: 22px;
  display: block;
  margin-top: -36px;
}

/* 二级标题 */
#nice h2 {
  position: relative;
	font-size: 20px;
}

/* 二级标题前缀，有兴趣加内容的可以魔改 */
#nice h2 .prefix {

}

/* 二级标题内容 */
#nice h2 .content {
	border-left: 4px solid;
  padding-left: 10px;
}

/* 一二级标题之间间距控制一下 */
#nice h1 + h2 {
  padding-top: 0;
}

/* 三级标题 */
#nice h3 {
  font-size: 16px;
}

/* 段落 */
#nice p {
  font-size: 16px;
  line-height: 2;
  font-weight: 400;
}

/* 段落间距控制 */
#nice p+p {
  margin-top: 16px;
}

/* 无序列表 */
#nice ul>li ul>li {
  list-style: circle;
}

/* 无序列表内容行高 */
#nice li section {
  line-height: 2;
}

/* 引用 */
#nice blockquote {
  border-left-color: #b2aec5;
  background: #fff9f9;
}

/* 引用文字 */
#nice blockquote p {
  color: #666;
  line-height: 2;
}

/* 链接 */
#nice a {
  color: #036aca;
  border-bottom: 0;
  font-weight: 400;
  text-decoration: none;
}

/* 加粗 */
#nice strong {
	background: linear-gradient(to right ,#3299d2,#efbdb5);
  color: #fff;
  font-weight: 400;
  padding: 0 4px;
  display: inline-block;
  border-radius: 4px;
  margin: 0 2px;
  letter-spacing: 1px;
}

/* 加粗斜体 */
#nice em strong {
  color: #fff;
}

/* 分隔线 */
#nice hr {
  border-top: 1px solid #135ce0;
}

/* 图片描述文字，隐藏了，如果需要，请删除display */
#nice figcaption {
  display: none;
  opacity: .6;
  margin-top: 12px;
  font-size: 12px;
}

/* 行内代码 */
#nice p code, li code {
  color: #1394d8;
  padding: 2px 6px;
  word-break: normal;
}

/* 表格 */
#nice table {
  border-spacing: 0;
}

/*
 * 表格内的单元格
 */
#nice table tr th {
  background-color: #d4f1ff;
}

/* 脚注文字 */
#nice .footnote-word {
  color: #135ce0;
  font-weight: 400;
}

/* 脚注上标 */
#nice .footnote-ref {
  color: #5ba1e2;
  font-weight: 400;
}

/* 参考资料 */
#nice .footnotes-sep:before {
  text-align: center;
  color: #135ce0;
  content: "参考";
}

/* 参考编号 */
#nice .footnote-num {
  color: #666;
}

/* 参考文字 */
#nice .footnote-item p { 
  color: #999;
  font-weight: 700;
  font-style: italic;
  font-size: 13px;
}

/* 参考解释 */
#nice .footnote-item p em {
  color: #3375e2;
  font-style: normal;
  margin-left: 4px;
}
```

## 主题预览

[“入坑”自媒体写作，我有干货与你分享](https://mp.weixin.qq.com/s/3VCR6kJwhNIUCiN-A-24pQ)

[用初中数学知识撸一个canvas环形进度条](https://juejin.im/post/5dc626125188253aec025a60)
