### ISSUE TITLE
自定义markdown css样式， 拷贝文章放到微信公众号显示异常

### ISSUE THREAD

**Issue by xiongxianzhu** [mdnice/markdown-nice#264]
**运行环境：**

|操作系统|浏览器|
|---|---|
|macOS|Chrome|

**修改css目的**

为了保留代码块的mac主题， 但不使用背景图片。原因： 因为公众号若开启了水印， 代码块的mac背景图片也有水印；其次， 每一个代码块都会使多媒体图库多了很多不必要的mac主题图片。

**我的css**

```css
#nice .custom {
    position: relative;
    padding: 2rem 0rem 0rem 0rem !important;
    border-radius: 0.35rem;
    tab-size: 4;
    background-color: #282c34;
}

#nice .custom::before {
    content: " ";
    position: absolute;
    border-radius: 50%;
    background: #ff5f56;
    width: 10px;
    height: 10px;
    top: 0;
    left: 12px;
    margin-top: 12px;
    -webkit-box-shadow: 16px 0 #ffbd2e, 32px 0 #27c93f;
    box-shadow: 16px 0 #ffbd2e, 32px 0 #27c93f;
}

#nice p code {
    padding: 1px 5px;
    top: 13px !important;
    font-family: Inconsolata, Monaco, Consolas, 'Courier New', Courier, monospace;
    font-size: 0.91rem;
    color: #e96900;
    background-color: #f8f8f8;
    border-radius: 2px;
}

#nice .custom code {
    padding: 5px 10px 15px 10px;
}

#nice p code, #nice li code {
    color: #e96900;
    background-color: #f8f8f8;
    border-radius: 2px;
}
```

**问题描述**

自定义css样式后， 在在线mdnice编辑器预览效果正常， 放到公众号上预览显示异常。

**效果图如下**
![image](https://user-images.githubusercontent.com/5771876/113823280-0abb8880-97b1-11eb-8229-b735225b93ef.png)
![image](https://user-images.githubusercontent.com/5771876/113823356-245cd000-97b1-11eb-9431-40a432c8ba8e.png)

**Comment by guanpengchn** [comment]
position不能用absolute

**Comment by xiongxianzhu** [comment]
那我试下position使用relative

**Comment by guanpengchn** [comment]
之前没花太多时间研究，如果能解决确实非常不错

**Comment by xiongxianzhu** [comment]
```css
#nice .custom {
    position: relative;
    /*padding: 2rem 0rem 0rem 0rem !important;*/
    border-radius: 0.35rem;
    tab-size: 4;
    background-color: #282c34;
}

#nice .custom::before {
    content: '';
    position: relative;
    border-radius: 50%;
    background: #ff5f56;
    width: 10px;
    height: 10px;
    margin-left: 12px;
    margin-top: 12px;
    -webkit-box-shadow: 16px 0 #ffbd2e, 32px 0 #27c93f;
    box-shadow: 16px 0 #ffbd2e, 32px 0 #27c93f;
}

#nice p code {
    padding: 1px 5px;
    top: 13px !important;
    font-family: Inconsolata, Monaco, Consolas, 'Courier New', Courier, monospace;
    font-size: 0.91rem;
    color: #e96900;
    background-color: #f8f8f8;
    border-radius: 2px;
}

#nice .custom code {
    padding: 15px 10px 15px 10px;
}

#nice p code, #nice li code {
    color: #e96900;
    background-color: #f8f8f8;
    border-radius: 2px;
}
```
position使用relative后， 在mdnice在线编辑器预览正常， 放到公众号上预览还是不正常。跟上面两个截图一样

**Comment by guanpengchn** [comment]
我猜测top也有问题？

**Comment by xiongxianzhu** [comment]
不是， 那个是行代码， 对了， 那个top我删除了， 之前用绝对布局， 忘记删除了

**Comment by guanpengchn** [comment]
你粘贴过去生效估计也是因为图片吧，那几个点本身好像并没生效

**Comment by xiongxianzhu** [comment]
我使用css样式实现的， 是会覆盖你们的图片那个样式的，这点我在预览， chrome审查元素可以看出是覆盖了

**Comment by guanpengchn** [comment]
编辑器的预览作用不大，要去检查粘贴到微信编辑器之后的预览，我看到的是用的还是图片

**Comment by xiongxianzhu** [comment]
从编辑器拷贝过去没有拷贝到我的样式过去。。

**Comment by guanpengchn** [comment]
好吧，今晚我看下吧

**Comment by xiongxianzhu** [comment]
从编辑器拷贝后的效果如下：

![image](https://user-images.githubusercontent.com/5771876/113831980-c0d7a000-97ba-11eb-967b-0f83b1da779e.png)
我调整拷贝后的样式效果如下：

![image](https://user-images.githubusercontent.com/5771876/113832190-f4b2c580-97ba-11eb-8748-f1054e16d60f.png)

核心在于width和height， 剩下就是调整位置了：
```
#nice .custom::before {
    content: '';
    position: relative;
    border-radius: 50%;
    background: #ff5f56;
    width: 10px;
    height: 10px;
    margin-left: 12px;
    margin-top: 12px;
    -webkit-box-shadow: 16px 0 #ffbd2e, 32px 0 #27c93f;
    box-shadow: 16px 0 #ffbd2e, 32px 0 #27c93f;
}
```
应该是拷贝的时候， 将我的css样式打乱了

**Comment by xiongxianzhu** [comment]
总算调好了， 主要加了`!important`以覆盖你们的样式, css如下：

```css
#nice .custom {
    position: relative;
    padding-top: 1px !important;
    border-radius: 0.35rem;
    tab-size: 4;
    background-color: #282c34;
}

#nice .custom::before {
    content: '';
    position: relative;
    border-radius: 50%;
    background: #ff5f56!important;
    width: 10px!important;
    height: 10px!important;
    margin-left: 12px!important;
    margin-top: 12px!important;
    -webkit-box-shadow: 16px 0 #ffbd2e, 32px 0 #27c93f;
    box-shadow: 16px 0 #ffbd2e, 32px 0 #27c93f;
}

#nice p code {
    padding: 1px 5px;
    font-family: Inconsolata, Monaco, Consolas, 'Courier New', Courier, monospace;
    font-size: 0.91rem;
    color: #e96900;
    background-color: #f8f8f8;
    border-radius: 2px;
}

#nice .custom code {
    padding: 15px 10px 15px 10px!important;
}

#nice p code, #nice li code {
    color: #e96900;
    background-color: #f8f8f8;
    border-radius: 2px;
}
```

效果图如下：
![image](https://user-images.githubusercontent.com/5771876/113835187-4f015580-97be-11eb-85be-8aec0a5834a6.png)
