### ISSUE TITLE
自定义新的css后复制文章一直处于复制状态

### ISSUE THREAD

**Issue by XiaoCaiTouYa** [mdnice/markdown-nice#75]
**运行环境：**

|操作系统|浏览器|
|---|---|
|win10|Chrome|

**Markdown文本内容：**

默认md

**Deprecation**
```html
[Deprecation] Element.createShadowRoot is deprecated and will be removed in M80, around February 2020. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.

Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure image '<URL>'. This content should also be served over HTTPS.
react-dom.production.min.js:2134 Mixed Content: The page at 'https://mdnice.com/' was loaded over HTTPS, but requested an insecure image 'http://a.hiphotos.baidu.com/image/h%3D300/sign=b38f3fc35b0fd9f9bf175369152cd42b/9a504fc2d5628535bdaac29e9aef76c6a6ef63c2.jpg'. This content should also be served over HTTPS.
cr @ react-dom.production.min.js:2134
button.js:358 Mixed Content: The page at 'https://mdnice.com/' was loaded over HTTPS, but requested an insecure image 'http://qiniu.mdnice.com/600b5c7b75570f57bae44ec0cbe498cc.png'. This content should also be served over HTTPS.
value @ button.js:358
button.js:358 Mixed Content: The page at 'https://mdnice.com/' was loaded over HTTPS, but requested an insecure image 'http://qiniu.mdnice.com/5c4c2d05f2765a46ed0e4fd4d4f3d73b.png'. This content should also be served over HTTPS.
value @ button.js:358
button.js:358 Mixed Content: The page at 'https://mdnice.com/' was loaded over HTTPS, but requested an insecure image 'http://qiniu.mdnice.com/600b5c7b75570f57bae44ec0cbe498cc.png'. This content should also be served over HTTPS.
value @ button.js:358
(index):25 Mixed Content: The page at 'https://mdnice.com/' was loaded over HTTPS, but requested an insecure image 'http://a.hiphotos.baidu.com/image/h%3D300/sign=b38f3fc35b0fd9f9bf175369152cd42b/9a504fc2d5628535bdaac29e9aef76c6a6ef63c2.jpg'. This content should also be served over HTTPS.
(anonymous) @ (index):25
helper.js:264 Mixed Content: The page at 'https://mdnice.com/' was loaded over HTTPS, but requested an insecure image 'http://a.hiphotos.baidu.com/image/h%3D300/sign=b38f3fc35b0fd9f9bf175369152cd42b/9a504fc2d5628535bdaac29e9aef76c6a6ef63c2.jpg'. This content should also be served over HTTPS.
```

**错误详情：**

```html
Uncaught TypeError: Cannot read property 'length' of undefined
    at inline.js:323
    at inline.js:87
    at Array.forEach (<anonymous>)
    at t (inline.js:31)
    at e.exports (cheerio.js:65)
    at Function.i.inlineContent (client.js:28)
    at e.t.solveHtml (Copy.js:51)
    at t.copy (Copy.js:60)
    at n.handleClick (button.js:226)
    at Object.<anonymous> (react-dom.production.min.js:81)
```

**下面是css**
---
```css
/* 全局属性
页边距 padding:30px;
全文字体 font-family:ptima-Regular;
英文换行 word-break:break-all;
*/

/*初始化格式*/
body,h1,h2,h3,p,ul,ol,dl,dd {
	margin:0;
}
.layout {
	line-height:1.6;
	font-family:"Helvetica Neue","PingFang SC","Hiragino Sans GB","Microsoft YaHei UI","Microsoft YaHei",Arial,sans-serif;
	font-size:16px;
	letter-spacing:0.034em;
	word-break:break-all;
}
p {
	margin:10px 10px;
	word-spacing:0.1em;
	color:rgb(74,74,74);
}
/* 一级标题 */
h1 {
	text-align:center;
	background-image:url(http://qiniu.mdnice.com/600b5c7b75570f57bae44ec0cbe498cc.png);
	background-position:center top;
	background-repeat:no-repeat;
	background-size:95px;
	line-height:95px;
	margin-top:38px;
	margin-bottom:10px;
}
/* 一级标题内容 */
h1 span {
	color:rgb(60,112,198);
	border-bottom:2px solid #3C7076;
}
/* 一级标题修饰 请参考有实例的主题 */
h1:after {
	}/* 二级标题 */
h2 {
	text-align:center;
	margin:0 auto;
	background-image:url(http://qiniu.mdnice.com/600b5c7b75570f57bae44ec0cbe498cc.png);
	background-position:center center;
	background-repeat:no-repeat;
	background-attachment:initial;
	background-origin:initial;
	background-clip:initial;
	background-size:63px;
	margin-top:38px;
	margin-bottom:10px;
}
/* 二级标题内容 */
h2:before {
	}h2 span {
	display:inline-block;
	height:38px;
	line-height:42px;
	color:rgb(60,112,198);
}
/* 三级标题 */
h3:before {
	content:url(http://qiniu.mdnice.com/5c4c2d05f2765a46ed0e4fd4d4f3d73b.png);
	display:inline-block;
	width:15px;
	height:15px;
	line-height:15px;
	margin-right:10px;
}
h3 {
	}/* 三级标题内容 */
h3 span {
	font-size:18px;
	font-weight:bolder;
	display:inline-block;
	padding-left:10px;
	margin-top:30px;
	margin-left:8px;
	color:rgb(60,112,198);
}
/* 三级标题修饰 请参考有实例的主题 */
h3:after {
	}/* 列表内容 */
li {
	font-size:13px;
}
/* 引用
 * 左边缘颜色 border-left-color:black;
	* 背景色 background:gray;
	*/
blockquote {
	font-style:normal;
	border-left:none;
	padding:19px;
	position:relative;
	font-size:15px;
	line-height:27px;
	margin-top:40px;
	margin-left:8px;
	margin-right:8px;
	background:rgb(239,239,239);
	/*  box-shadow:#84A1A8 0px 10px 15px;
	*/
}
/*
blockquote:before {
	content:"“ ";
	display:inline;
	color:rgb(89,89,89);
	font-size:4em;
	font-family:Arial,serif;
	line-height:1em;
	font-weight:700;
}
*/
/* 引用文字 */
blockquote p {
	color:rgb(89,89,89);
	font-size:13px;
	display:inline;
}
/*
blockquote:after {
	content:"”";
	float:right;
	display:inline;
	color:rgb(89,89,89);
	font-size:3em;
	line-height:1em;
	font-weight:500;
}
*/
/* 链接 */
a {
	color:rgb(248,57,41);
	text-decoration:none;
	border-bottom:0px solid #ff3502;
	font-family:STHeitiSC-Light;
}
/* 加粗 */
strong {
	font-weight:border;
	color:#4a4a4a;
}
/* 斜体 */
em {
	color:rgb(248,57,41);
	letter-spacing:0.3em;
}
/* 加粗斜体 */
strong em {
	color:rgb(248,57,41);
	letter-spacing:0.3em;
}
/* 删除线 */
del {
	}/* 分隔线
 * 粗细、样式和颜色
 * border-top:1px solid #3e3e3e;
	*/
hr {
	height:1px;
	padding:0;
	border:none;
	border-top:medium solidid #333;
	text-align:center;
	background-image:linear-gradient(to right,rgba(248,57,41,0),rgba(248,57,41,0.75),rgba(248,57,41,0));
}
/* 图片
 * 宽度 width:80%;
	* 居中 margin:0 auto;
	* 居左 margin:0 0;
	*/
img {
	border-radius:12px;
	display:block;
	margin:20px auto;
	width:95%;
	object-fit:contain;
	/*  box-shadow:#84A1A8 0px 10px 15px;
	*/
}
/* 图片描述文字 */
figcaption {
	display:block;
	font-size:12px;
	font-family:PingFangSC-Light;
}
/* 行内代码 */
p code,li code {
	color:rgb(271,93,108);
}
/* 非微信代码块
 * 代码块不换行 display:-webkit-box !important;
	* 代码块换行 display:block;
	*/
pre code {
	}/*
 * 表格内的单元格
 * 字体大小 font-size:16px;
	* 边框 border:1px solid #ccc;
	* 内边距 padding:5px 10px;
	*/
table tr th,table tr td {
	font-size:14px;
}
/* 脚注文字 */
.footnote-word {
	color:rgb(248,57,41);
}
/* 脚注上标 */
.footnote-ref {
	color:rgb(248,57,41);
}
/*脚注链接样式*/
.footnote-item em {
	color:#6E1E51;
	font-size:12px;
}
/* "参考资料"四个字 */
.footnotes-sep {
	display:inline-block;
	padding-left:20px;
}
/* 参考资料编号 */
.footnote-num {
	}/* 参考资料文字 */
.footnote-item p {
	}/* 参考资料解释 */
.footnote-item p em {
	}/* 行间公式
 * 最大宽度 max-width:300% !important;
	*/
.block-equation svg {
	}/* 行内公式
 */
.inline-equation svg {
	}
```
